CREATE SCHEMA IF NOT EXISTS mynt AUTHORIZATION DBA;

CREATE TABLE mynt.rule (
	id INTEGER IDENTITY PRIMARY KEY,
	rule_name VARCHAR(100) NOT NULL,
	priority INTEGER NOT NULL,
	type VARCHAR(10) NOT NULL,
	min NUMERIC(18,2),
	max NUMERIC(18,2),
	rate NUMERIC(18,2),
	reject_flag BOOLEAN
)